name: Deploy to Onestack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Dokploy deployment
        run: |
          curl -s -X POST \
            "https://console.onestack.run/api/deploy/HL2q0L8CGp1oZt1BvOW1s" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.ONESTACK_API_KEY }}" \
            -d '{"ref":"refs/heads/main"}'
